name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Run frontend lint
        run: yarn lint
        working-directory: frontend

      - name: Run frontend format check
        run: yarn format --check
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: pip install -r backend/fastapi/requirements.txt
        working-directory: backend/fastapi

      - name: Run backend lint (Flake8)
        run: flake8 .
        working-directory: backend/fastapi

      - name: Run backend lint (Pylint)
        run: pylint --rcfile=pylintrc .
        working-directory: backend/fastapi

      - name: Run backend format check (Black)
        run: black --check .
        working-directory: backend/fastapi